# -*- coding: utf-8 -*-
"""day 7 i

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hwzr_6F-Zfa8ActYHKdw6gI46FQUBEhe
"""

from google import genai

client = genai.Client(
    api_key="your api key"
)

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Explain what Artificial Intelligence is in simple words."
)

print(response.text)

from google import genai
from PIL import Image

# Initialize Gemini Client
client = genai.Client(api_key="your api key")

# Load resume image (assuming PDF is converted to image for now)
image = Image.open("resume.jpg")

prompt = """
You are an AI resume analyzer.

Analyze this resume and extract the following information:

1.  **Contact Information**
    -   Name
    -   Phone Number
    -   Email
    -   LinkedIn Profile (if available)
    -   Portfolio/Website (if available)

2.  **Summary/Objective**
    -   Summarize the candidate's professional objective or summary statement.

3.  **Work Experience**
    -   For each position, list:
        -   Job Title
        -   Company Name
        -   Location
        -   Dates of Employment
        -   Key Responsibilities and Achievements (bullet points)

4.  **Education**
    -   For each educational entry, list:
        -   Degree/Certification
        -   Institution Name
        -   Location
        -   Graduation Date (or expected date)

5.  **Skills**
    -   List all technical and soft skills identified.

6.  **Projects/Portfolios (if available)**
    -   Summarize key projects and their impact.

7.  **Certifications/Awards (if available)**
    -   List any relevant certifications or awards.

Do NOT provide opinions or judgments about the candidate. If information is missing, clearly state that.
"""

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=[prompt, image]
)

print(response.text)

!pip install faiss-cpu
!pip install -q google-genai sentence-transformers faiss-cpu

from google import genai
from PIL import Image
from google.colab import files
import io

client = genai.Client(api_key="your api")

uploaded = files.upload()

if uploaded:
    image_name = list(uploaded.keys())[0]
    image_bytes = uploaded[image_name]
    image = Image.open(io.BytesIO(image_bytes))
    print(f"Successfully loaded {image_name}")
else:
    print(f"Error: No image file uploaded. Please upload an image file.")
    raise FileNotFoundError("No image file uploaded.")

caption_prompt = "Generate a concise and creative caption for this image."

response_caption = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=[caption_prompt, image]
)

print("Generated Caption:")
print(response_caption.text)