# -*- coding: utf-8 -*-
"""DAY 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18h9OrI4Po26emRZjdq-uWmK8LjTU18pM
"""

!pip install googletrans==3.1.0a0

import nltk
from google.colab import files
import io
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords, wordnet
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag

# Download NLTK resources (run only once)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng') # Corrected: Needed for pos_tag
nltk.download('punkt_tab')

# Open the file and read its content
with open('/content/text.txt','r') as file:
  text = file.read()
print("Original Text:")
print(text)

# Step 1: Tokenization
tokens = word_tokenize(text)
print("\nTokens:")
print(tokens)

# Step 2: Stop Word Removal
stop_words = set(stopwords.words('english'))
# Convert to lowercase and filter non-alphabetic words
filtered_words = [word.lower() for word in tokens if word.lower() not in stop_words and word.isalpha()]

print("\nAfter Stop Word Removal (excluding non-alphabetic and lowercased):")
print(filtered_words)

# Step 3: Stemming
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in filtered_words]

print("\nStemmed Words:")
print(stemmed_words)

# Step 4: Lemmatization
lemmatizer = WordNetLemmatizer()

# Function to convert NLTK POS tags to WordNet POS tags
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN # Default to noun if not found

lemmatized_words = []
# Get POS tags for filtered words
pos_tags = pos_tag(filtered_words)

for word, tag in pos_tags:
    w_pos = get_wordnet_pos(tag)
    lemmatized_words.append(lemmatizer.lemmatize(word, pos=w_pos))

print("\nLemmatized Words (with POS tagging):")
print(lemmatized_words)

from googletrans import Translator

translator = Translator()

# Translate the 'text' variable to Chinese (Simplified)
translated_text = translator.translate(text, dest='zh-cn').text

print("\nTranslated Text (Chinese Simplified):")
print(translated_text)

# ---------------------------------------------
# Simple Rule-Based Chatbot
# ---------------------------------------------

print("=" * 50)
print("🤖 Welcome to Simple NLP Chatbot")
print("Type 'bye' to exit.")
print("=" * 50)

while True:
    user = input("\nYou: ").lower()

    if user == "hello" or user == "hi":
        print("Bot: Hello! How can I help you?")

    elif "how are you" in user:
        print("Bot: I am doing great. Thank you for asking!")

    elif "your name" in user:
        print("Bot: My name is AI Chatbot.")

    elif "college" in user:
        print("Bot: I am designed to assist students in learning NLP.")

    elif "python" in user:
        print("Bot: Python is one of the most popular programming languages for AI and NLP.")

    elif "nlp" in user:
        print("Bot: NLP stands for Natural Language Processing.")

    elif "ai" in user:
        print("Bot: AI stands for Artificial Intelligence.")

    elif "thank" in user:
        print("Bot: You're welcome!")

    elif user == "bye":
        print("Bot: Goodbye! Have a nice day.")
        break

    else:
        print("Bot: Sorry, I don't understand that. Please try another question.")

!pip install openai-whisper
!pip install torch

import whisper

model = whisper.load_model("base")

result = model.transcribe("audio.mp3")

print(result["text"])

